globalThis.CodenamesLibrary = (() => {
  "use strict";

  const WORD_CATEGORY = Object.freeze({
    id: "codenames-words",
    groupId: "codenames",
    name: "Words",
    description: "A large Codenames-style word bank used only by Codenames."
  });

  const WORDS = Object.freeze([
  "airport",
  "alley",
  "arena",
  "attic",
  "avenue",
  "bank",
  "barn",
  "beach",
  "border",
  "bridge",
  "bunker",
  "cabin",
  "camp",
  "canal",
  "canyon",
  "castle",
  "cave",
  "cellar",
  "chapel",
  "city",
  "cliff",
  "coast",
  "courtroom",
  "crossroads",
  "desert",
  "dock",
  "embassy",
  "factory",
  "farm",
  "field",
  "forest",
  "fortress",
  "garden",
  "gate",
  "harbour",
  "highway",
  "hill",
  "hospital",
  "hotel",
  "island",
  "jungle",
  "laboratory",
  "lake",
  "library",
  "lighthouse",
  "mansion",
  "market",
  "mine",
  "monastery",
  "mountain",
  "museum",
  "oasis",
  "office",
  "orchard",
  "palace",
  "park",
  "pier",
  "prison",
  "pyramid",
  "ranch",
  "reef",
  "river",
  "road",
  "school",
  "station",
  "street",
  "studio",
  "swamp",
  "temple",
  "theatre",
  "tower",
  "tunnel",
  "valley",
  "village",
  "volcano",
  "warehouse",
  "waterfall",
  "well",
  "zoo",
  "acorn",
  "ash",
  "aurora",
  "avalanche",
  "bark",
  "blossom",
  "boulder",
  "branch",
  "breeze",
  "brook",
  "bush",
  "cactus",
  "cloud",
  "clover",
  "coral",
  "crater",
  "crystal",
  "dawn",
  "dew",
  "dune",
  "dusk",
  "earth",
  "eclipse",
  "ember",
  "feather",
  "fire",
  "flame",
  "flower",
  "fog",
  "fossil",
  "frost",
  "galaxy",
  "geyser",
  "glacier",
  "grass",
  "gravel",
  "horizon",
  "ice",
  "lightning",
  "magma",
  "meadow",
  "meteor",
  "mist",
  "moon",
  "moss",
  "mud",
  "ocean",
  "pebble",
  "planet",
  "pond",
  "puddle",
  "rain",
  "rainbow",
  "rock",
  "root",
  "sand",
  "shadow",
  "shell",
  "sky",
  "smoke",
  "snow",
  "soil",
  "space",
  "spark",
  "star",
  "steam",
  "stone",
  "storm",
  "sun",
  "thunder",
  "tide",
  "tornado",
  "tree",
  "wave",
  "wind",
  "winter",
  "wood",
  "alligator",
  "ant",
  "ape",
  "badger",
  "bat",
  "bear",
  "bee",
  "beetle",
  "bird",
  "bison",
  "butterfly",
  "camel",
  "cat",
  "caterpillar",
  "chicken",
  "cobra",
  "crab",
  "crocodile",
  "crow",
  "deer",
  "dog",
  "dolphin",
  "donkey",
  "dove",
  "dragonfly",
  "duck",
  "eagle",
  "eel",
  "elephant",
  "falcon",
  "fish",
  "flamingo",
  "fly",
  "fox",
  "frog",
  "goat",
  "goose",
  "gorilla",
  "hamster",
  "hawk",
  "hedgehog",
  "hippo",
  "horse",
  "jellyfish",
  "kangaroo",
  "kitten",
  "koala",
  "ladybird",
  "leopard",
  "lion",
  "lizard",
  "lobster",
  "llama",
  "monkey",
  "moth",
  "mouse",
  "octopus",
  "otter",
  "owl",
  "panda",
  "parrot",
  "peacock",
  "penguin",
  "pig",
  "pigeon",
  "pony",
  "rabbit",
  "raccoon",
  "rat",
  "raven",
  "rhino",
  "salmon",
  "seal",
  "shark",
  "sheep",
  "snail",
  "snake",
  "spider",
  "squid",
  "squirrel",
  "swan",
  "tiger",
  "tortoise",
  "turtle",
  "whale",
  "wolf",
  "worm",
  "zebra",
  "almond",
  "apple",
  "apricot",
  "avocado",
  "bacon",
  "bagel",
  "banana",
  "bean",
  "berry",
  "biscuit",
  "bread",
  "broccoli",
  "burger",
  "cabbage",
  "cake",
  "candy",
  "carrot",
  "cereal",
  "cheese",
  "cherry",
  "chilli",
  "chocolate",
  "coconut",
  "coffee",
  "cookie",
  "corn",
  "cream",
  "cucumber",
  "curry",
  "doughnut",
  "egg",
  "garlic",
  "grape",
  "honey",
  "jam",
  "jelly",
  "kiwi",
  "lemon",
  "lettuce",
  "lime",
  "mango",
  "melon",
  "milk",
  "mushroom",
  "mustard",
  "noodle",
  "olive",
  "onion",
  "orange",
  "pancake",
  "pasta",
  "peach",
  "peanut",
  "pear",
  "pepper",
  "pickle",
  "pie",
  "pineapple",
  "pizza",
  "plum",
  "popcorn",
  "potato",
  "pumpkin",
  "raisin",
  "raspberry",
  "rice",
  "salad",
  "sandwich",
  "sausage",
  "soup",
  "spice",
  "spinach",
  "strawberry",
  "sugar",
  "sushi",
  "tea",
  "tomato",
  "vanilla",
  "waffle",
  "watermelon",
  "wheat",
  "yoghurt",
  "anchor",
  "anvil",
  "arrow",
  "axe",
  "badge",
  "bag",
  "ball",
  "balloon",
  "barrel",
  "basket",
  "bell",
  "belt",
  "blanket",
  "block",
  "board",
  "bolt",
  "book",
  "bottle",
  "bowl",
  "box",
  "bracelet",
  "brick",
  "broom",
  "brush",
  "bucket",
  "button",
  "cage",
  "candle",
  "card",
  "carpet",
  "chain",
  "chair",
  "chalk",
  "clock",
  "coin",
  "comb",
  "compass",
  "crown",
  "cup",
  "cushion",
  "dagger",
  "dice",
  "dish",
  "doll",
  "door",
  "drum",
  "envelope",
  "fan",
  "flag",
  "fork",
  "frame",
  "gem",
  "glass",
  "glove",
  "hammer",
  "hat",
  "hook",
  "horn",
  "key",
  "kite",
  "knife",
  "ladder",
  "lamp",
  "lantern",
  "lock",
  "magnet",
  "map",
  "mask",
  "medal",
  "mirror",
  "needle",
  "net",
  "newspaper",
  "package",
  "padlock",
  "paint",
  "paper",
  "pen",
  "pencil",
  "pillow",
  "pin",
  "pipe",
  "plate",
  "plug",
  "pocket",
  "radio",
  "ring",
  "rope",
  "ruler",
  "saddle",
  "sail",
  "saw",
  "scarf",
  "scissors",
  "screw",
  "shield",
  "shovel",
  "sign",
  "skate",
  "skull",
  "soap",
  "spoon",
  "spring",
  "stamp",
  "string",
  "sword",
  "table",
  "ticket",
  "torch",
  "towel",
  "toy",
  "trap",
  "trophy",
  "umbrella",
  "vase",
  "wallet",
  "watch",
  "whistle",
  "window",
  "wire",
  "actor",
  "agent",
  "artist",
  "astronaut",
  "athlete",
  "baker",
  "barber",
  "boss",
  "captain",
  "chef",
  "child",
  "clown",
  "coach",
  "cowboy",
  "dancer",
  "detective",
  "doctor",
  "driver",
  "drummer",
  "farmer",
  "firefighter",
  "guard",
  "judge",
  "king",
  "knight",
  "leader",
  "magician",
  "mayor",
  "mechanic",
  "miner",
  "model",
  "monk",
  "nurse",
  "officer",
  "painter",
  "pilot",
  "pirate",
  "player",
  "poet",
  "police",
  "president",
  "prince",
  "princess",
  "queen",
  "referee",
  "reporter",
  "robot",
  "sailor",
  "scientist",
  "singer",
  "soldier",
  "spy",
  "student",
  "surgeon",
  "teacher",
  "thief",
  "tourist",
  "trainer",
  "vampire",
  "vet",
  "waiter",
  "warrior",
  "witch",
  "wizard",
  "worker",
  "writer",
  "ankle",
  "arm",
  "beard",
  "blood",
  "bone",
  "boot",
  "brain",
  "cap",
  "cheek",
  "chin",
  "coat",
  "collar",
  "dress",
  "ear",
  "elbow",
  "eye",
  "face",
  "finger",
  "foot",
  "glasses",
  "hair",
  "hand",
  "head",
  "heart",
  "heel",
  "helmet",
  "jacket",
  "knee",
  "lip",
  "mouth",
  "muscle",
  "neck",
  "nose",
  "pyjamas",
  "shirt",
  "shoe",
  "skin",
  "skirt",
  "sleeve",
  "sock",
  "stomach",
  "suit",
  "thumb",
  "tie",
  "toe",
  "tongue",
  "tooth",
  "trousers",
  "uniform",
  "wing",
  "ambulance",
  "bicycle",
  "boat",
  "bus",
  "carriage",
  "cart",
  "crane",
  "ferry",
  "helicopter",
  "jet",
  "lorry",
  "motorcycle",
  "plane",
  "rocket",
  "scooter",
  "ship",
  "sledge",
  "submarine",
  "taxi",
  "tractor",
  "train",
  "tram",
  "truck",
  "van",
  "yacht",
  "engine",
  "wheel",
  "platform",
  "runway",
  "cockpit",
  "garage",
  "port",
  "terminal",
  "atom",
  "battery",
  "beam",
  "cable",
  "camera",
  "capsule",
  "circuit",
  "code",
  "computer",
  "console",
  "data",
  "device",
  "diamond",
  "experiment",
  "film",
  "fuel",
  "gear",
  "gravity",
  "laser",
  "lens",
  "machine",
  "microscope",
  "molecule",
  "motor",
  "network",
  "orbit",
  "oxygen",
  "pixel",
  "radar",
  "satellite",
  "screen",
  "signal",
  "socket",
  "software",
  "switch",
  "telescope",
  "virus",
  "website",
  "plasma",
  "quantum",
  "sensor",
  "server",
  "tablet",
  "keyboard",
  "printer",
  "drone",
  "album",
  "band",
  "ballet",
  "cartoon",
  "cinema",
  "circus",
  "comic",
  "concert",
  "dance",
  "drawing",
  "fairy tale",
  "gallery",
  "game",
  "guitar",
  "joke",
  "melody",
  "movie",
  "music",
  "novel",
  "opera",
  "painting",
  "photo",
  "piano",
  "poem",
  "poster",
  "puzzle",
  "riddle",
  "rhythm",
  "scene",
  "sculpture",
  "song",
  "stage",
  "story",
  "television",
  "trumpet",
  "violin",
  "voice",
  "character",
  "costume",
  "drama",
  "festival",
  "magic",
  "microphone",
  "orchestra",
  "portrait",
  "script",
  "show",
  "sketch",
  "soundtrack",
  "alien",
  "angel",
  "armour",
  "army",
  "battle",
  "beast",
  "centaur",
  "dragon",
  "dungeon",
  "dwarf",
  "empire",
  "fairy",
  "ghost",
  "giant",
  "goblin",
  "gold",
  "griffin",
  "hero",
  "kingdom",
  "legend",
  "mermaid",
  "monster",
  "mummy",
  "ninja",
  "oracle",
  "phoenix",
  "potion",
  "relic",
  "samurai",
  "skeleton",
  "spell",
  "spirit",
  "throne",
  "treasure",
  "troll",
  "unicorn",
  "Viking",
  "wand",
  "zombie",
  "answer",
  "balance",
  "beauty",
  "beginning",
  "belief",
  "bravery",
  "chance",
  "change",
  "choice",
  "circle",
  "clue",
  "colour",
  "danger",
  "day",
  "dream",
  "energy",
  "error",
  "escape",
  "family",
  "fear",
  "freedom",
  "future",
  "gift",
  "goal",
  "luck",
  "memory",
  "message",
  "mystery",
  "night",
  "noise",
  "number",
  "order",
  "peace",
  "plan",
  "point",
  "power",
  "question",
  "race",
  "reason",
  "rule",
  "secret",
  "shape",
  "silence",
  "speed",
  "strength",
  "time",
  "truth",
  "value",
  "victory",
  "warning",
  "wonder",
  "world",
  "zero",
  "bounce",
  "break",
  "build",
  "burn",
  "catch",
  "chase",
  "climb",
  "close",
  "crash",
  "crawl",
  "cross",
  "dig",
  "dive",
  "draw",
  "drink",
  "drive",
  "drop",
  "fall",
  "fight",
  "find",
  "freeze",
  "grow",
  "hide",
  "hit",
  "jump",
  "kick",
  "laugh",
  "lift",
  "look",
  "march",
  "open",
  "play",
  "pull",
  "push",
  "read",
  "ride",
  "roll",
  "run",
  "search",
  "shake",
  "shoot",
  "sing",
  "sink",
  "skip",
  "sleep",
  "slide",
  "smile",
  "spin",
  "stand",
  "swim",
  "swing",
  "talk",
  "throw",
  "touch",
  "travel",
  "turn",
  "walk",
  "wash",
  "whisper",
  "write",
  "aluminium",
  "bronze",
  "cardboard",
  "clay",
  "cloth",
  "coal",
  "copper",
  "cotton",
  "dust",
  "fabric",
  "iron",
  "leather",
  "marble",
  "metal",
  "oil",
  "plastic",
  "rubber",
  "salt",
  "silk",
  "silver",
  "steel",
  "tin",
  "water",
  "wax",
  "wool",
  "afternoon",
  "autumn",
  "calendar",
  "century",
  "evening",
  "Friday",
  "hour",
  "midnight",
  "minute",
  "Monday",
  "morning",
  "month",
  "noon",
  "Saturday",
  "season",
  "second",
  "summer",
  "Sunday",
  "Thursday",
  "Tuesday",
  "Wednesday",
  "week",
  "year",
  "yesterday",
  "tomorrow",
  "archery",
  "badminton",
  "baseball",
  "basketball",
  "billiards",
  "boxing",
  "chess",
  "cricket",
  "cycling",
  "darts",
  "football",
  "golf",
  "gymnastics",
  "hockey",
  "judo",
  "karate",
  "lacrosse",
  "marathon",
  "netball",
  "poker",
  "racing",
  "rugby",
  "running",
  "sailing",
  "skating",
  "skiing",
  "snooker",
  "squash",
  "surfing",
  "swimming",
  "tennis",
  "volleyball",
  "wrestling",
  "bathroom",
  "bedroom",
  "blackboard",
  "classroom",
  "corridor",
  "cupboard",
  "desk",
  "dining room",
  "fence",
  "floor",
  "hall",
  "homework",
  "kitchen",
  "lesson",
  "playground",
  "roof",
  "shelf",
  "stairs",
  "study",
  "wall",
  "worksheet",
  "address",
  "alphabet",
  "call",
  "chat",
  "email",
  "emoji",
  "language",
  "letter",
  "name",
  "news",
  "note",
  "password",
  "phone",
  "phrase",
  "postcard",
  "reply",
  "speech",
  "text",
  "word",
  "amber",
  "aqua",
  "beige",
  "black",
  "blue",
  "brown",
  "crimson",
  "cyan",
  "green",
  "grey",
  "indigo",
  "ivory",
  "magenta",
  "maroon",
  "navy",
  "pink",
  "purple",
  "red",
  "scarlet",
  "turquoise",
  "violet",
  "white",
  "yellow",
  "bright",
  "dark",
  "glow",
  "light",
  "shade",
  "shine",
  "business",
  "capital",
  "club",
  "company",
  "country",
  "court",
  "crowd",
  "election",
  "government",
  "law",
  "money",
  "nation",
  "party",
  "shop",
  "team",
  "trade",
  "union",
  "vote",
  "war",
  "abbey",
  "accident",
  "acid",
  "adventure",
  "alarm",
  "angle",
  "antler",
  "apron",
  "arcade",
  "arch",
  "bamboo",
  "banquet",
  "barge",
  "basil",
  "basin",
  "beacon",
  "blade",
  "blizzard",
  "bloom",
  "blueprint",
  "bonefire",
  "booklet",
  "bottlecap",
  "bubble",
  "bulldozer",
  "bullet",
  "caravan",
  "carnival",
  "cathedral",
  "ceiling",
  "chainmail",
  "chimney",
  "claw",
  "cloak",
  "coastline",
  "cobweb",
  "comet",
  "cottage",
  "cube",
  "curtain",
  "cyclone",
  "daylight",
  "deck",
  "dentist",
  "depot",
  "diary",
  "dinosaur",
  "disc",
  "disguise",
  "domino",
  "doorway",
  "echo",
  "emerald",
  "emperor",
  "fingerprint",
  "fireplace",
  "fireworks",
  "fountain",
  "freezer",
  "gargoyle",
  "gateway",
  "general",
  "globe",
  "greenhouse",
  "hammerhead",
  "handcuff",
  "harvest",
  "honeycomb",
  "iceberg",
  "igloo",
  "ink",
  "insect",
  "jackpot",
  "jewel",
  "joystick",
  "kettle",
  "lagoon",
  "landmark",
  "lava",
  "leaf",
  "lipstick",
  "mailbox",
  "maze",
  "minefield",
  "moonlight",
  "mosquito",
  "motorway",
  "necklace",
  "nightclub",
  "notebook",
  "parachute",
  "passport",
  "pavement",
  "pearl",
  "perfume",
  "picnic",
  "prism",
  "propeller",
  "railway",
  "razor",
  "record",
  "remote",
  "restaurant",
  "ribbon",
  "rooftop",
  "sapphire",
  "schoolbag",
  "screwdriver",
  "seagull",
  "shipwreck",
  "shoelace",
  "skyscraper",
  "snowball",
  "snowman",
  "spaceship",
  "spiderweb",
  "staircase",
  "starfish",
  "suitcase",
  "sunflower",
  "supermarket",
  "swordfish",
  "tent",
  "thunderbolt",
  "toolbox",
  "toothpaste",
  "triangle",
  "typewriter",
  "universe",
  "wallpaper",
  "windmill",
  "workshop",
  "zipper",
  "ancient",
  "angry",
  "automatic",
  "awake",
  "basic",
  "beautiful",
  "bitter",
  "blind",
  "brave",
  "broken",
  "calm",
  "central",
  "cheap",
  "clean",
  "clear",
  "clever",
  "cold",
  "complete",
  "cool",
  "crooked",
  "dangerous",
  "deep",
  "double",
  "dry",
  "empty",
  "equal",
  "false",
  "famous",
  "fast",
  "final",
  "flat",
  "free",
  "fresh",
  "full",
  "golden",
  "good",
  "grand",
  "happy",
  "hard",
  "heavy",
  "hidden",
  "high",
  "hollow",
  "hot",
  "huge",
  "hungry",
  "invisible",
  "junior",
  "large",
  "late",
  "left",
  "little",
  "long",
  "loose",
  "loud",
  "lucky",
  "major",
  "modern",
  "narrow",
  "natural",
  "new",
  "noisy",
  "normal",
  "old",
  "opposite",
  "pale",
  "perfect",
  "poor",
  "quick",
  "quiet",
  "rare",
  "rich",
  "right",
  "rough",
  "round",
  "royal",
  "safe",
  "sharp",
  "short",
  "silent",
  "simple",
  "slow",
  "small",
  "smooth",
  "soft",
  "solid",
  "sour",
  "special",
  "square",
  "strange",
  "strong",
  "sweet",
  "tall",
  "thick",
  "thin",
  "tiny",
  "top",
  "true",
  "warm",
  "weak",
  "wet",
  "wild",
  "wooden",
  "young"
]);
  const SUPPLEMENTAL_TEXT = Object.freeze({
  "integers": [
    "−100",
    "−75",
    "−50",
    "−40",
    "−30",
    "−25",
    "−18",
    "−15",
    "−10",
    "−6",
    "−5",
    "−4",
    "−2",
    "−1",
    "3",
    "4",
    "5",
    "6",
    "8",
    "9",
    "10",
    "11",
    "13",
    "14",
    "15",
    "18",
    "20",
    "21",
    "24",
    "27",
    "30",
    "32",
    "40",
    "42",
    "50",
    "72",
    "99",
    "121",
    "169",
    "1000"
  ],
  "fractions": [
    "1/5",
    "1/6",
    "1/8",
    "1/10",
    "2/3",
    "2/7",
    "3/5",
    "3/8",
    "4/5",
    "5/6",
    "5/7",
    "7/8",
    "9/10",
    "11/12",
    "4/3",
    "5/4",
    "7/4",
    "3/2",
    "5/2",
    "2 1/4",
    "2 1/2",
    "2 3/4",
    "3 1/3",
    "3 1/2",
    "4 1/4",
    "7/10",
    "3/10",
    "1/12",
    "5/12",
    "7/12"
  ],
  "decimals": [
    "0.01",
    "0.02",
    "0.05",
    "0.08",
    "0.12",
    "0.15",
    "0.2",
    "0.3",
    "0.35",
    "0.45",
    "0.6",
    "0.65",
    "0.7",
    "0.8",
    "0.9",
    "1.05",
    "1.25",
    "1.5",
    "1.75",
    "2.4",
    "2.75",
    "3.14",
    "4.5",
    "5.05",
    "6.25",
    "7.8",
    "9.99",
    "10.1",
    "12.5",
    "100.01"
  ],
  "percentages": [
    "1%",
    "2%",
    "5%",
    "12%",
    "15%",
    "20%",
    "30%",
    "33%",
    "35%",
    "45%",
    "60%",
    "62.5%",
    "65%",
    "70%",
    "80%",
    "85%",
    "90%",
    "95%",
    "99%",
    "110%",
    "125%",
    "150%",
    "200%",
    "250%",
    "0.5%",
    "7.5%",
    "17.5%",
    "37.5%",
    "66⅔%",
    "87.5%"
  ],
  "number-words": [
    "odd",
    "even",
    "composite",
    "natural number",
    "whole number",
    "rational",
    "irrational",
    "real number",
    "decimal place",
    "place value",
    "digit",
    "power",
    "index",
    "base",
    "reciprocal",
    "common factor",
    "highest common factor",
    "lowest common multiple",
    "divisible",
    "remainder",
    "sequence",
    "term-to-term rule",
    "square root",
    "cube root",
    "standard form",
    "significant figure",
    "rounding",
    "estimate",
    "ascending",
    "descending"
  ],
  "fdp-words": [
    "proper fraction",
    "improper fraction",
    "mixed number",
    "unit fraction",
    "vulgar fraction",
    "decimal fraction",
    "terminating decimal",
    "recurring decimal",
    "percentage change",
    "percentage increase",
    "percentage decrease",
    "reverse percentage",
    "ratio",
    "proportion",
    "part",
    "whole",
    "convert",
    "common denominator",
    "lowest terms",
    "equivalent fraction",
    "decimal point",
    "hundredth",
    "thousandth",
    "one tenth",
    "one hundredth",
    "one thousandth",
    "of",
    "per cent",
    "simplest form",
    "fraction bar"
  ],
  "mathematical-symbols": [
    "≠",
    "≈",
    "∝",
    "∞",
    "π",
    "∑",
    "∴",
    "∵",
    "±",
    "∓",
    "∠",
    "°",
    "%",
    "‰",
    "|x|",
    "∈",
    "∉",
    "⊂",
    "∪",
    "∩",
    "∅",
    "→",
    "↔",
    "≡",
    "∫",
    "∂",
    "!",
    "∥",
    "⊥",
    "∼"
  ],
  "operation-words": [
    "add",
    "subtract",
    "multiply",
    "divide",
    "increase",
    "decrease",
    "double",
    "triple",
    "halve",
    "share equally",
    "remainder",
    "power",
    "root",
    "square",
    "cube",
    "inverse",
    "reciprocal",
    "calculate",
    "evaluate",
    "combine",
    "split",
    "take away",
    "times",
    "groups of",
    "raise to the power",
    "subtract from",
    "add on",
    "difference between",
    "multiply by",
    "divide by"
  ],
  "algebra-expressions": [
    "x+1",
    "x−1",
    "2x+3",
    "5x−4",
    "7−x",
    "10−2x",
    "x/3",
    "(x−2)/5",
    "4(x−1)",
    "2(x+5)",
    "x²−4",
    "x²+2x",
    "x²−9",
    "3x²+1",
    "xy+2",
    "a−b",
    "2a+3b",
    "m+n",
    "3p−q",
    "y=2x+1",
    "x>15",
    "x≤4",
    "2x=10",
    "x+y=12",
    "a²+b²",
    "√x",
    "1/x",
    "x³",
    "(x+1)²",
    "2(x−3)+5"
  ],
  "algebra-words": [
    "formula",
    "identity",
    "unknown",
    "like terms",
    "linear",
    "quadratic",
    "sequence",
    "function",
    "input",
    "output",
    "mapping",
    "gradient",
    "intercept",
    "coordinate",
    "graph",
    "axis",
    "origin",
    "constant",
    "bracket",
    "factor",
    "root",
    "solution",
    "balance",
    "rearrange",
    "subject",
    "simultaneous",
    "eliminate",
    "inequation",
    "inequality sign",
    "substitution"
  ],
  "2d-shapes": [
    "equilateral triangle",
    "isosceles triangle",
    "scalene triangle",
    "right-angled triangle",
    "quadrilateral",
    "heptagon",
    "nonagon",
    "decagon",
    "dodecagon",
    "oval",
    "ellipse",
    "sector",
    "segment",
    "arc",
    "chord",
    "diameter",
    "radius",
    "tangent",
    "arrowhead",
    "regular polygon",
    "irregular polygon",
    "concave polygon",
    "convex polygon",
    "star",
    "crescent",
    "cross",
    "annulus",
    "parabola",
    "rhombus",
    "deltoid"
  ],
  "3d-shapes": [
    "triangular pyramid",
    "pentagonal prism",
    "hexagonal prism",
    "octagonal prism",
    "pentagonal pyramid",
    "hexagonal pyramid",
    "hemisphere",
    "frustum",
    "torus",
    "ellipsoid",
    "octahedron",
    "dodecahedron",
    "icosahedron",
    "prism",
    "pyramid",
    "polyhedron",
    "net",
    "face",
    "edge",
    "vertex",
    "cross-section",
    "cone frustum",
    "hollow cylinder",
    "capsule",
    "wedge",
    "square prism",
    "rectangular pyramid",
    "oblique prism",
    "regular tetrahedron",
    "truncated cone"
  ],
  "data-words": [
    "frequency",
    "relative frequency",
    "cumulative frequency",
    "grouped data",
    "discrete data",
    "continuous data",
    "categorical data",
    "quantitative data",
    "qualitative data",
    "bias",
    "questionnaire",
    "survey",
    "experiment",
    "hypothesis",
    "trend",
    "outlier",
    "positive correlation",
    "negative correlation",
    "no correlation",
    "stem-and-leaf",
    "box plot",
    "histogram",
    "frequency polygon",
    "line of best fit",
    "probability scale",
    "sample space",
    "tree diagram",
    "Venn diagram",
    "mutually exclusive",
    "independent event"
  ],
  "flags": [
    "Scotland",
    "Wales",
    "England",
    "Northern Ireland",
    "Norway",
    "Sweden",
    "Finland",
    "Denmark",
    "Iceland",
    "Netherlands",
    "Belgium",
    "Portugal",
    "Switzerland",
    "Austria",
    "Greece",
    "Poland",
    "Ukraine",
    "Mexico",
    "Argentina",
    "Chile",
    "New Zealand",
    "Egypt",
    "Nigeria",
    "Kenya",
    "Morocco",
    "Turkey",
    "Pakistan",
    "Thailand",
    "Vietnam",
    "Indonesia"
  ],
  "sports": [
    "archery",
    "athletics",
    "badminton",
    "baseball",
    "basketball",
    "boxing",
    "canoeing",
    "climbing",
    "cricket",
    "curling",
    "cycling",
    "darts",
    "diving",
    "fencing",
    "football",
    "golf",
    "gymnastics",
    "handball",
    "hockey",
    "horse racing",
    "judo",
    "karate",
    "lacrosse",
    "netball",
    "rowing",
    "rugby",
    "sailing",
    "skateboarding",
    "skiing",
    "snooker",
    "squash",
    "surfing",
    "swimming",
    "table tennis",
    "taekwondo",
    "tennis",
    "volleyball",
    "weightlifting",
    "wrestling"
  ]
});
  const SUPPLEMENTAL_COLOURS = Object.freeze([
  [
    "amber",
    "#ffbf00"
  ],
  [
    "aquamarine",
    "#7fffd4"
  ],
  [
    "azure",
    "#007fff"
  ],
  [
    "burgundy",
    "#800020"
  ],
  [
    "cerise",
    "#de3163"
  ],
  [
    "charcoal",
    "#36454f"
  ],
  [
    "coral",
    "#ff7f50"
  ],
  [
    "cream",
    "#fffdd0"
  ],
  [
    "emerald",
    "#50c878"
  ],
  [
    "fuchsia",
    "#ff00ff"
  ],
  [
    "indigo",
    "#4b0082"
  ],
  [
    "ivory",
    "#fffff0"
  ],
  [
    "khaki",
    "#c3b091"
  ],
  [
    "lavender",
    "#e6e6fa"
  ],
  [
    "lilac",
    "#c8a2c8"
  ],
  [
    "maroon",
    "#800000"
  ],
  [
    "mint",
    "#98ff98"
  ],
  [
    "mustard",
    "#ffdb58"
  ],
  [
    "navy",
    "#000080"
  ],
  [
    "ochre",
    "#cc7722"
  ],
  [
    "peach",
    "#ffe5b4"
  ],
  [
    "plum",
    "#dda0dd"
  ],
  [
    "rose",
    "#ff007f"
  ],
  [
    "ruby",
    "#e0115f"
  ],
  [
    "saffron",
    "#f4c430"
  ],
  [
    "salmon",
    "#fa8072"
  ],
  [
    "scarlet",
    "#ff2400"
  ],
  [
    "teal",
    "#008080"
  ],
  [
    "turquoise",
    "#40e0d0"
  ],
  [
    "vermilion",
    "#e34234"
  ]
]);

  const CUSTOM_ITEMS = [];
  const CUSTOM_ITEM_BY_ID = new Map();

  function slugify(value) {
    return String(value)
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "item";
  }

  function makeItem({
    id,
    label,
    categoryId,
    subcategoryId = categoryId,
    displayType = "text",
    displayValue = label,
    spokenName = label,
    colourValue = null,
    tags = [],
    familyId = id
  }) {
    return Object.freeze({
      id,
      label,
      groupId: categoryId === WORD_CATEGORY.id
        ? "codenames"
        : "codenames-supplement",
      categoryId,
      subcategoryId,
      displayType,
      displayValue,
      spokenName,
      tags: Object.freeze([...tags, "codenames-only"]),
      difficulty: "easy",
      recognisability: "high",
      familyId,
      svgKey: null,
      flagCode: null,
      colourValue,
      wikipediaTitle: null,
      imagePath: null,
      approvalStatus: "approved",
      classroomSafe: true,
      codenamesOnly: true
    });
  }

  function addCustomItem(entry) {
    if (CUSTOM_ITEM_BY_ID.has(entry.id)) return;
    CUSTOM_ITEMS.push(entry);
    CUSTOM_ITEM_BY_ID.set(entry.id, entry);
  }

  WORDS.forEach((word, index) => {
    addCustomItem(makeItem({
      id: `codenames-word-${String(index + 1).padStart(4, "0")}-${slugify(word)}`,
      label: word,
      categoryId: WORD_CATEGORY.id,
      tags: ["wordbank"]
    }));
  });

  Object.entries(SUPPLEMENTAL_TEXT).forEach(([categoryId, labels]) => {
    labels.forEach((label, index) => {
      addCustomItem(makeItem({
        id: `codenames-extra-${categoryId}-${String(index + 1).padStart(3, "0")}-${slugify(label)}`,
        label,
        categoryId,
        tags: ["supplemental"]
      }));
    });
  });

  SUPPLEMENTAL_COLOURS.forEach(([label, colourValue], index) => {
    addCustomItem(makeItem({
      id: `codenames-extra-colours-${String(index + 1).padStart(3, "0")}-${slugify(label)}`,
      label,
      categoryId: "colours",
      displayType: "colour",
      colourValue,
      tags: ["supplemental", "colour"]
    }));
  });

  function getSpecialCategory() {
    return { ...WORD_CATEGORY };
  }

  function getItemById(id) {
    return CUSTOM_ITEM_BY_ID.get(id) ||
      globalThis.ClueItemGenerator?.getItemById(id) ||
      null;
  }

  function getBaseItems(categoryIds) {
    if (!globalThis.ClueItemGenerator) {
      throw new Error("ClueItemGenerator must be loaded first.");
    }

    const baseIds = categoryIds.filter(
      (id) => id !== WORD_CATEGORY.id
    );

    if (baseIds.length === 0) return [];

    return ClueItemGenerator.getItems({
      categoryIds: baseIds,
      minimumRecognisability: "medium",
      maximumDifficulty: "hard"
    });
  }

  function getCustomItems(categoryIds) {
    const wanted = new Set(categoryIds);
    return CUSTOM_ITEMS.filter((entry) => wanted.has(entry.categoryId));
  }

  function getPool(categoryIds) {
    const selected = [...new Set(categoryIds || [])];
    const combined = [
      ...getBaseItems(selected),
      ...getCustomItems(selected)
    ];

    const seenIds = new Set();
    const seenCategoryLabels = new Set();

    return combined.filter((entry) => {
      if (!entry || seenIds.has(entry.id)) return false;

      const labelKey = `${entry.categoryId}:${String(entry.label).trim().toLowerCase()}`;
      if (seenCategoryLabels.has(labelKey)) return false;

      seenIds.add(entry.id);
      seenCategoryLabels.add(labelKey);
      return true;
    });
  }

  function generateBoard(count = 25, options = {}) {
    const wanted = Math.max(4, Math.min(40, Number(count) || 25));
    const categoryIds = [...new Set(options.categoryIds || [])];

    if (categoryIds.length === 0) {
      throw new Error("Select at least one category.");
    }

    const pool = getPool(categoryIds);

    if (pool.length < wanted) {
      throw new Error(
        `Only ${pool.length} distinct items are available from the selected categories, but ${wanted} are required.`
      );
    }

    const buckets = new Map();
    categoryIds.forEach((categoryId) => buckets.set(categoryId, []));

    shuffle(pool).forEach((entry) => {
      if (!buckets.has(entry.categoryId)) buckets.set(entry.categoryId, []);
      buckets.get(entry.categoryId).push(entry);
    });

    const selected = [];
    const selectedIds = new Set();
    const selectedFamilies = new Set();
    const categoryOrder = shuffle(
      [...buckets.keys()].filter((id) => buckets.get(id).length > 0)
    );

    let madeProgress = true;
    while (selected.length < wanted && madeProgress) {
      madeProgress = false;

      for (const categoryId of categoryOrder) {
        const bucket = buckets.get(categoryId);
        let choice = null;

        while (bucket.length > 0 && !choice) {
          const candidate = bucket.shift();
          if (selectedIds.has(candidate.id)) continue;
          if (selectedFamilies.has(candidate.familyId)) continue;
          choice = candidate;
        }

        if (!choice) continue;

        selected.push(choice);
        selectedIds.add(choice.id);
        selectedFamilies.add(choice.familyId);
        madeProgress = true;

        if (selected.length >= wanted) break;
      }
    }

    if (selected.length < wanted) {
      for (const entry of shuffle(pool)) {
        if (selected.length >= wanted) break;
        if (selectedIds.has(entry.id)) continue;
        selected.push(entry);
        selectedIds.add(entry.id);
      }
    }

    return shuffle(selected).slice(0, wanted);
  }

  async function renderItem(itemOrId, container, options = {}) {
    const entry = typeof itemOrId === "string"
      ? getItemById(itemOrId)
      : itemOrId;

    if (!entry) throw new Error("Unknown Codenames item.");
    return ClueItemGenerator.renderItem(entry, container, options);
  }

  function getCategoryCount(categoryId) {
    return getPool([categoryId]).length;
  }

  function shuffle(values) {
    const result = [...values];
    for (let index = result.length - 1; index > 0; index--) {
      const randomIndex = Math.floor(Math.random() * (index + 1));
      [result[index], result[randomIndex]] = [result[randomIndex], result[index]];
    }
    return result;
  }

  return Object.freeze({
    getSpecialCategory,
    getItemById,
    getPool,
    getCategoryCount,
    generateBoard,
    renderItem,
    wordCount: WORDS.length
  });
})();
