/* Generated by tools/update_soundboard.py. */

globalThis.SOUNDBOARD_SOUNDS = Object.freeze(
[
  {
    "key": "W",
    "name": "wompwomp",
    "sources": [
      "../../assets/sounds/W wompwomp.mp3"
    ]
  },
  {
    "key": "R",
    "name": "rickroll",
    "sources": [
      "../../assets/sounds/R rickroll.mp3"
    ]
  },
  {
    "key": "Y",
    "name": "yippee",
    "sources": [
      "../../assets/sounds/Y yippee.mp3"
    ]
  },
  {
    "key": "A",
    "name": "amongus",
    "sources": [
      "../../assets/sounds/A amongus.mp3"
    ]
  },
  {
    "key": "S",
    "name": "getitstarted",
    "sources": [
      "../../assets/sounds/S getitstarted.mp3"
    ]
  },
  {
    "key": "D",
    "name": "dundundun",
    "sources": [
      "../../assets/sounds/D dundundun.mp3"
    ]
  },
  {
    "key": "G",
    "name": "correct",
    "sources": [
      "../../assets/sounds/G correct.mp3"
    ]
  },
  {
    "key": "L",
    "name": "2000yearslater",
    "sources": [
      "../../assets/sounds/L 2000yearslater.mp3"
    ]
  },
  {
    "key": "X",
    "name": "wrong",
    "sources": [
      "../../assets/sounds/X wrong.mp3"
    ]
  },
  {
    "key": "C",
    "name": "countdown",
    "sources": [
      "../../assets/sounds/C countdown.mp3"
    ]
  },
  {
    "key": "V",
    "name": "vineboom",
    "sources": [
      "../../assets/sounds/V vineboom.mp3"
    ]
  },
  {
    "key": "M",
    "name": "metalpipe",
    "sources": [
      "../../assets/sounds/M metalpipe.mp3"
    ]
  }
]
);
