#!/usr/bin/env python3
"""Build js/soundboard-sounds.js from audio files in assets.

Preferred filename format:
    W wompwomp.mp3
    K anotherone.mp3

The first letter selects the keyboard key. The remaining filename becomes the
label shown under the key. Files may be stored in assets/sounds or directly in
assets. Only one sound may be assigned to each letter.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOUND_DIRECTORIES = (
    PROJECT_ROOT / "assets" / "sounds",
    PROJECT_ROOT / "assets",
)
OUTPUT_PATH = PROJECT_ROOT / "js" / "soundboard-sounds.js"

SUPPORTED_EXTENSIONS = {
    ".mp3",
    ".wav",
    ".ogg",
    ".m4a",
    ".aac",
    ".flac",
}

QWERTY_ORDER = "QWERTYUIOPASDFGHJKLZXCVBNM"

# These allow the original starter files to keep their requested keys even if
# they have not yet been renamed to include an explicit key prefix.
STARTER_KEYS = {
    "wompwomp": "W",
    "dundundun": "D",
    "vineboom": "V",
    "amongus": "A",
    "yippee": "Y",
    "anotherone": "K",
    "correct": "G",
    "metalpipe": "M",
    "countdown": "C",
    "whatsgoingon": "O",
    "wrong": "X",
}


def main() -> int:
    audio_files = discover_audio_files()

    if not audio_files:
        print("No sound files were found in assets/sounds or assets.")
        print("Add files such as 'W wompwomp.mp3', then run this again.")
        return 1

    sounds = []
    seen_keys: dict[str, Path] = {}
    errors: list[str] = []

    for file_path in audio_files:
        parsed = parse_sound_file(file_path)

        if parsed is None:
            continue

        key, name = parsed

        if key in seen_keys:
            errors.append(
                f"Key {key} is assigned twice:\n"
                f"  {seen_keys[key].relative_to(PROJECT_ROOT)}\n"
                f"  {file_path.relative_to(PROJECT_ROOT)}"
            )
            continue

        seen_keys[key] = file_path
        relative_path = file_path.relative_to(PROJECT_ROOT).as_posix()

        sounds.append({
            "key": key,
            "name": name,
            "sources": [f"../../{relative_path}"],
        })

    if errors:
        print("The manifest was not changed because duplicate keys were found:\n")
        print("\n\n".join(errors))
        return 1

    if not sounds:
        print("Audio files were found, but none followed the naming convention.")
        print("Use a letter followed by a space, hyphen or underscore, for example:")
        print("  Q question-time.mp3")
        return 1

    order = {letter: index for index, letter in enumerate(QWERTY_ORDER)}
    sounds.sort(key=lambda sound: order[sound["key"]])

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render_manifest(sounds), encoding="utf-8")

    print(f"Updated {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")
    print(f"Included {len(sounds)} sound{'s' if len(sounds) != 1 else ''}.")

    for sound in sounds:
        print(f"  {sound['key']} — {sound['name']}")

    return 0


def discover_audio_files() -> list[Path]:
    files: set[Path] = set()

    sounds_directory = SOUND_DIRECTORIES[0]
    if sounds_directory.exists():
        for file_path in sounds_directory.rglob("*"):
            if is_supported_audio(file_path):
                files.add(file_path.resolve())

    assets_directory = SOUND_DIRECTORIES[1]
    if assets_directory.exists():
        for file_path in assets_directory.iterdir():
            if is_supported_audio(file_path):
                files.add(file_path.resolve())

    return sorted(files, key=lambda path: path.name.casefold())


def is_supported_audio(file_path: Path) -> bool:
    return (
        file_path.is_file()
        and file_path.suffix.casefold() in SUPPORTED_EXTENSIONS
    )


def parse_sound_file(file_path: Path) -> tuple[str, str] | None:
    stem = file_path.stem.strip()

    prefixed = re.fullmatch(r"([A-Za-z])[\s_-]+(.+)", stem)
    if prefixed:
        key = prefixed.group(1).upper()
        name = clean_label(prefixed.group(2))
        return (key, name) if name else None

    starter_key = STARTER_KEYS.get(stem.casefold())
    if starter_key:
        return starter_key, clean_label(stem)

    print(
        "Skipping "
        f"{file_path.relative_to(PROJECT_ROOT)}: "
        "the filename does not begin with a key and separator."
    )
    return None


def clean_label(value: str) -> str:
    label = re.sub(r"[_-]+", " ", value)
    label = re.sub(r"\s+", " ", label)
    return label.strip()


def render_manifest(sounds: list[dict[str, object]]) -> str:
    json_text = json.dumps(
        sounds,
        ensure_ascii=False,
        indent=2,
    )

    return (
        "/* Generated by tools/update_soundboard.py. */\n\n"
        "globalThis.SOUNDBOARD_SOUNDS = Object.freeze(\n"
        f"{json_text}\n"
        ");\n"
    )


if __name__ == "__main__":
    sys.exit(main())
